### PR TITLE
Merge edge

### PR DESCRIPTION
**Pull request by mariogrip**
**This needs force push**

### CODE REVIEW

**Comment by Flohack74** [comment]
...and please add again newest Jenkinsfile ^^

**Comment by Flohack74** [comment]
And please consider newer version as in https://github.com/ubports/mobile-broadband-provider-info-src-packaging/tree/xenial_-_android9

**Comment by mariogrip** [comment]
Done @Flohack74 :)

**Review by Flohack74 — APPROVED** [review]

**Comment by Flohack74** [comment]
Uh what happened, conflicts ;)

**Comment by mariogrip** [comment]
Merged

**Comment by Flohack74** [comment]
If you merged this in another PR then please link it to here, or why was this just closed without merging?

**Pull request closed without merging**
